#!/bin/sh

# Set these paths appropriately

BIN="/home/chloe/Documents/snipfeed/prod/tagging_system/french/treetagger/bin"
CMD="/home/chloe/Documents/snipfeed/prod/tagging_system/french/treetagger/cmd"
LIB="/home/chloe/Documents/snipfeed/prod/tagging_system/french/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/middle-high-german-abbreviations
PARFILE=${LIB}/middle-high-german.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
