#!/bin/sh

# Set these paths appropriately

BIN="/home/chloe/Documents/snipfeed/prod/tagging_system/french/treetagger/bin"
CMD="/home/chloe/Documents/snipfeed/prod/tagging_system/french/treetagger/cmd"
LIB="/home/chloe/Documents/snipfeed/prod/tagging_system/french/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/english-abbreviations
PARFILE=${LIB}/english.par

$TOKENIZER -e -a $ABBR_LIST $* |
# remove empty lines
grep -v '^$' |
# tagging
$TAGGER $OPTIONS $PARFILE | 
perl -pe 's/\tV[BDHV]/\tVB/;s/\tIN\/that/\tIN/;'
