#!/bin/sh

# Set these paths appropriately

BIN="/home/chloe/Documents/snipfeed/prod/tagging_system/french/treetagger/bin"
CMD="/home/chloe/Documents/snipfeed/prod/tagging_system/french/treetagger/cmd"
LIB="/home/chloe/Documents/snipfeed/prod/tagging_system/french/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
