#!/bin/sh

# Set these paths appropriately

BIN="/home/chloe/Documents/snipfeed/prod/tagging_system/french/treetagger/bin"
CMD="/home/chloe/Documents/snipfeed/prod/tagging_system/french/treetagger/cmd"
LIB="/home/chloe/Documents/snipfeed/prod/tagging_system/french/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ancient-greek.par

$TOKENIZER $* |
# tagging
$TAGGER $OPTIONS $PARFILE

